package Admin;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Font;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.Timer;

public class AdminDashboard extends javax.swing.JFrame {
    
    private boolean isSidebarVisible = true;
    private final int SIDEBAR_WIDTH = 140;
    private Timer animationTimer;
    private JButton toggleButton;

    public AdminDashboard() {
        initComponents();
        setupToggleButton();
        setSize(1000, 600); 
        setLocationRelativeTo(null);
    }
    
    private void setupToggleButton() {
        toggleButton = new JButton("☰");
        toggleButton.setBackground(new Color(51, 51, 51)); 
        toggleButton.setForeground(Color.WHITE);
        toggleButton.setFocusPainted(false);
        toggleButton.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        buttonPanel.setBackground(Color.WHITE);
        buttonPanel.add(toggleButton);
        
        Dashboard.add(buttonPanel, BorderLayout.NORTH);
        
        toggleButton.addActionListener(e -> toggleSidebar());
    }
    
    private void toggleSidebar() {
        if (animationTimer != null && animationTimer.isRunning()) {
            return; 
        }
        
      
        final int steps = 20; 
        final int delay = 10; 
        final int targetWidth = isSidebarVisible ? 0 : SIDEBAR_WIDTH;
        final int startWidth = isSidebarVisible ? SIDEBAR_WIDTH : 0;
        
        animationTimer = new Timer(delay, new ActionListener() {
            int step = 0;
            
            @Override
            public void actionPerformed(ActionEvent e) {
                step++;
               
                float progress = (float) step / steps;
                int newWidth = (int) (startWidth + (targetWidth - startWidth) * progress);
                
               
                SideBarPanel.setBounds(0, 0, newWidth, 600);
                Dashboard.setBounds(newWidth, 0, 1000 - newWidth, 600);
                
                getContentPane().revalidate();
                
              
                if (step >= steps) {
                    ((Timer)e.getSource()).stop();
                    isSidebarVisible = !isSidebarVisible;
                    SideBarPanel.setVisible(isSidebarVisible);
                }
            }
        });
        
        SideBarPanel.setVisible(true);
        animationTimer.start();
    }
    
    private void updateContentPanel(String menuItem) {
        Dashboard.removeAll();
        
        
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        buttonPanel.setBackground(Color.WHITE);
        buttonPanel.add(toggleButton);
        
        JLabel contentLabel = new JLabel(menuItem + " Page", SwingConstants.CENTER);
        contentLabel.setFont(new Font("Roboto", Font.BOLD, 28));
        
        Dashboard.add(buttonPanel, BorderLayout.NORTH);
        Dashboard.add(contentLabel, BorderLayout.CENTER);
        
        Dashboard.revalidate();
        Dashboard.repaint();
    }

    
  
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        SideBarPanel = new javax.swing.JPanel();
        DashboardButtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setPreferredSize(new java.awt.Dimension(1000, 600));
        Dashboard.setLayout(null);

        SideBarPanel.setBackground(new java.awt.Color(51, 51, 51));

        DashboardButtn.setText("Dashboard");
        DashboardButtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtnActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout SideBarPanelLayout = new javax.swing.GroupLayout(SideBarPanel);
        SideBarPanel.setLayout(SideBarPanelLayout);
        SideBarPanelLayout.setHorizontalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DashboardButtn, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        SideBarPanelLayout.setVerticalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarPanelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(DashboardButtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        Dashboard.add(SideBarPanel);
        SideBarPanel.setBounds(0, 0, 140, 610);

        getContentPane().add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DashboardButtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardButtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("theme");
        UIManager.put("defeaultFont", new Font(FlatRobotoFont.FAMILY,Font.PLAIN,13));
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton DashboardButtn;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
